name: Sync upstream

on:
  push:
    branches: [main]

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Sync upstream
        run: bash script/sync-upstream.sh
        env:
          DESTINATION_BRANCH: main
          DESTINATION_DIRECTORY: "ei"
          DESTINATION_REPOSITORY: j143/janardhan.page
          PAT: ${{ secrets.PAT }}
          SOURCE_DIRECTORY: book